articles/urls.py
from django.urls import path
from . import views

app_name = 'articles' # 처음부터 url app name

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:pk>/comment/<int:c_pk>/delete/', views.comment_del, name='comment_del'),
]


# url은 사용자가 보낸 요청!!!!!!!!!!!!!

pairing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment = models.TextField()

# 그이후 python manage.py showmigrations로 migrate반영되었는지 확인

articles/forms.py
from django import forms
from .models import Article, Comment
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content')
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommentForm

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles,
        }
    return render (request, 'articles/index.html', context)

def create(request):
    # POST 요청이면,
    if request.method == 'POST':
        article_form = ArticleForm(request.POST)
        # valid?
        if article_form.is_valid():
            # valid하면, 저장
            article = article_form.save()
            return redirect('articles:detail', article.pk)
    # GET 요청이면,
    else:
        article_form = ArticleForm()
    context = {
        'article_form' : article_form
    }
    return render(request, 'articles/form.html', context)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    context = {
        'article' : article,
        'comment_form' : comment_form,
    }
    return render(request, 'articles/detail.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')

def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, instance=article)
        if article_form.is_valid():
            article = article_form.save()
            return redirect('articles:detail', article.pk)
    else:
        article_form = ArticleForm(instance=article)
    context = {
        'article' : article,
        'article_form' : article_form
    }
    return render(request, 'articles/form.html', context)

def comment_create(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid:
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.save()
    return redirect('articles:detail', article.pk)

def comment_del(request, pk, c_pk):
    if request.method == 'POST':
        comment = Comment.objects.get(pk=c_pk)
        comment.delete()
        return redirect('articles:detail', pk)
    

articles/templates/articles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <img src="{% static 'articles/images/bg.jpg' %}" alt="">
    {% block body %}
    {% endblock %}
</body>
</html>

articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% load static %}
{% block body %}
    <h1>{{article.title}}</h1>
    <hr>
    <p>{{article.content}}</p>
    <hr>
    <a href="{% url 'articles:delete' article.pk %}"><button>삭제하기</button></a>
    <a href="{% url 'articles:update' article.pk %}"><button>수정하기</button></a>
    <hr>
    <h4>댓글</h3>
    <form action="{% url 'articles:comment_create' article.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form }}
        <input type="submit" value="댓글달기">
    </form>
    <hr>
    <ol>{% for comment in article.comment_set.all %}
        <li>  {{comment.comment}}</li>
        <form action="{% url 'articles:comment_del' article.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="댓글삭제">
        </form>
        {% endfor %}
    </ol>
    <a href="{% url 'articles:index' %}">목록</a>
{% endblock %}

articles/templates/articles/form.html
{% extends 'articles/base.html' %}
{% block body %}
  <form action="" method="POST">
    {% csrf_token %}
    {{article_form}}
    <input type="submit" value="저장하기">
  </form>
{% endblock %}

articles/templates/articles/index.html
{% extends 'articles/base.html'%}
{% load static %}
{% block body %}
    <h1>게시판 환영!!!</h1>
    {% for i in articles %}
        <p><a href="{{i.pk}}">{{i.title}}</a></p>
        <p>{{i.content}}</p>
    {% endfor %}
    <a href="{% url 'articles:create' %}"><button>글 작성</button></a>
{% endblock %}